# Documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '11:00'
      timezone: 'Europe/Zurich'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    reviewers:
      - '@UN-OCHA/hpc-js-reviewers'
    groups:
      bunyan:
        applies-to: version-updates
        patterns:
          - '*bunyan'
      pg:
        applies-to: version-updates
        patterns:
          - '*pg'
      jest:
        applies-to: version-updates
        patterns:
          - '*jest'
    ignore:
      # HPC-9080: Don't upgrade Hapi version until migrating to Apollo Server 4
      - dependency-name: '@hapi/hapi'
        versions: ['>= 21.0.0']
      - dependency-name: '@types/hapi__hapi'
      # ESLint is a peer dependency of `@unocha/hpc-repo-tools`
      - dependency-name: 'eslint'
      # Dependency `type-graphql` still doesn't support GraphQL v16
      - dependency-name: 'graphql'
        versions: ['>= 16.0.0']
      # Typescript is a peer dependency of `@unocha/hpc-repo-tools`
      - dependency-name: 'typescript'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '11:00'
      timezone: 'Europe/Zurich'
    reviewers:
      - '@UN-OCHA/hpc-js-reviewers'
