services:
  api:
    build:
      context: .
      dockerfile: ./env/api/Dockerfile
    ports:
      - '4000:5100'
    volumes:
      - .:/srv/www
      - ./env/api/node.sh:/etc/services.d/node/run
    environment:
      - LOG_MODE=devServer
      - POSTGRES_SERVER=postgres://demo:demo@host.docker.internal:5432/demo
      - PORT=5100
      - NODE_ENV=development
      - NAME=hpc-api-standalone-development
      - POSTGRES_LOGGING=0
      - ROOT_URL=http://service.hpc.vm/
      - AUTHBASE_URL=http://api.hid.vm
      - WAIT_HOSTS=host.docker.internal:5432
      - WAIT_HOSTS_TIMEOUT=120
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:11.7
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
    ports:
      - 5432:5432
    volumes:
      - hpc_postgres_db:/var/lib/postgresql/data
      - ./backups:/backups
volumes:
  hpc_postgres_db:
