version: '3.8'
services:
  api:
    container_name: hpc_api
    build:
      context: .
      dockerfile: ./env/api/Dockerfile
    ports:
      - '4000:5100'
    volumes:
      - .:/srv/www
      - ./env/api/node.sh:/etc/services.d/node/run
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=postgres://demo:demo@host.docker.internal:5432/demo
      - PORT=5100
      - NODE_ENV=development
      - NAME=${NAME}
      - POSTGRES_LOGGING=${POSTGRES_LOGGING}
      - ROOT_URL=${ROOT_URL}
      - AUTHBASE_URL=${AUTHBASE_URL}
      - WAIT_HOSTS=host.docker.internal:5432
      - WAIT_HOSTS_TIMEOUT=120
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:12.4-alpine
    container_name: hpc_postgres_db
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
    ports:
      - 5432:5432
    volumes:
      - hpc_postgres_db:/var/lib/postgresql/data
      - ./backups:/backups
volumes:
  hpc_postgres_db:
