
version: "3.3"
services:
  db:
    image: postgres:12.4-alpine
    container_name: hpc_v3_db
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
    ports:
      - 5432:5432

    volumes:
      - hpc_v3_db:/var/lib/postgresql/data
      - ./data/backups:/backups
  api:
    build: .
    container_name: hpc_v3_api
    env_file:
      - .env
    environment:
      - DEV_DB_HOST=host.docker.internal
      - DNSDOCK_NAME=node
      - DNSDOCK_IMAGE=hpc
      - PORT=5100
      - NODE_ENV=dockerdev
      - NAME=${NAME}
      - POSTGRES_LOGGING=${POSTGRES_LOGGING}
      - ROOT_URL=${ROOT_URL}
      - AUTHBASE_URL=${AUTHBASE_URL}
      - WAIT_HOSTS=pgsql:5432
      - WAIT_HOSTS_TIMEOUT=120
    volumes:
      - ./:/usr/src/app
    ports:
      - 4000:5100
    depends_on:
      - db

  redis:
    image: bitnami/redis:6.2
    restart: always
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes # Basically No auth. For development only
      - REDIS_PASSWORD=password123 # If you login via the tty shell, use the command redis-cli -a $REDIS_PASSWORD to access the cli
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  hpc_v3_db:
  redis_data:

