version: "3.8"
services:
  db:
    image: postgres:12.4-alpine
    container_name: newServiceDB
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
    ports:
      - 5437:5432
    volumes:
      - newServiceDBData:/var/lib/postgresql/data
    networks:
      - newService
  api:
    build: .
    container_name: newServiceAPI
    env_file:
      - .env
    environment:
      - DEV_DB_HOST=host.docker.internal
      - DNSDOCK_NAME=node
      - DNSDOCK_IMAGE=hpc
      - PORT=5100
      - NODE_ENV=dockerdev
      - NAME=${NAME}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_LOGGING=${POSTGRES_LOGGING}
      - ROOT_URL=${ROOT_URL}
      - AUTHBASE_URL=${AUTHBASE_URL}
      - WAIT_HOSTS=pgsql:5432
      - WAIT_HOSTS_TIMEOUT=120
    volumes:
      - ./:/usr/src/app
    ports:
      - 4000:5100
    depends_on:
      - db
    networks:
      - service
      - newService
volumes:
  newServiceDBData:
networks:
  service:
    external:
      name: hpcservice_service
  newService:
