openapi: 3.0.0
info:
  title: HPC Service V3
  version: 3.0.0
paths:
  /rest/all-plans:
    get:
      operationId: allPlansQuery
      parameters:
        - in: query
          name: year
          required: false
          schema:
            type: number
            format: float
      responses:
        '200':
          description: Get all the plans
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plan'
components:
  schemas:
    Query:
      type: object
      required:
        - allPlans
      properties:
        allPlans:
          type: array
          items:
            $ref: '#/components/schemas/Plan'
          description: Get all the plans
    Plan:
      type: object
      required:
        - id
        - name
        - year
        - fundingRequirements
        - funding
        - clusters
        - caseloads
      properties:
        id:
          type: string
        name:
          type: string
        year:
          type: number
          format: float
        fundingRequirements:
          $ref: '#/components/schemas/PlanFunding'
        funding:
          $ref: '#/components/schemas/PlanFunding'
        clusters:
          type: array
          items:
            $ref: '#/components/schemas/PlanCluster'
        caseloads:
          type: array
          items:
            $ref: '#/components/schemas/PlanCaseload'
    PlanFunding:
      type: object
      required:
        - amountUSD
        - breakdown
      properties:
        amountUSD:
          type: number
          format: float
        breakdown:
          $ref: '#/components/schemas/PlanFundingBreakdown'
    PlanFundingBreakdown:
      type: object
      properties:
        byCluster:
          type: array
          items:
            $ref: '#/components/schemas/PlanFundingBreakdownCluster'
    PlanFundingBreakdownCluster:
      type: object
      required:
        - amountUSD
        - cluster
      properties:
        amountUSD:
          type: number
          format: float
        cluster:
          $ref: '#/components/schemas/PlanCluster'
    PlanCluster:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    PlanCaseload:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        population:
          type: number
          format: float
        affected:
          type: number
          format: float
          description: How many people are affected by the humanitarian crisis
        inNeed:
          type: number
          format: float
        targeted:
          type: number
          format: float
          description: How many people does this plan aim to target
        expectedReach:
          type: number
          format: float
