name: 'Setup External Repos'
description: 'Clone repositories specified in manifest file'
author: 'Sam Lanning <sam@samlanning.com>'
runs:
  using: 'node16'
  main: 'setup.js'
branding:
  icon: 'download-cloud'
  color: 'purple'
