name: CI Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  workflow:
    name: Code Checks
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: TypeScript compiler checks
        run: npm run check-types
      - name: Linting checks
        run: npm run lint
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run Unit Tests
        run: ./bin/test.sh
