name: CI Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  workflow:
    name: Linting Checks
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Linting checks
        run: npm run lint
