name: CI Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  workflow:
    name: Code Checks
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: TypeScript compiler checks
        run: npm run check-types
      - name: Linting checks
        run: npm run lint
